name: link_checkPR

on:
  pull_request:
    branches:
      - main

jobs:
  linkChecker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --accept=200,403,429 --base . --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'
          token: ${{ secrets.CUSTOM_TOKEN }}
          fail: true
