#Checks links in a PR to ensure they are valid. If link is valid but failing, it can be added to the .lycheeignore file
#Code source: https://github.com/lycheeverse/lychee-action/issues/238

name: link check on PR

on:
  pull_request:
    branches: [main]
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v34
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --accept=200,403,429 --base . --verbose --no-progress ${{ steps.changed-files.outputs.all_changed_files }}
          token: ${{ secrets.CUSTOM_TOKEN }}
          fail: true
