name: link_check

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "35 17 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          # Check all markdown, html and reStructuredText files in repo (default)
          args: --base . --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'
          # Use json as output format (instead of markdown)
          format: json
          # Use different output file path
          output: /tmp/foo.txt
          # Use a custom GitHub token, which 
          token: ${{ secrets.CUSTOM_TOKEN }}
          # Don't fail action on broken links
          fail: false

     # - name: Create Issue From File
     #   if: env.lychee_exit_code != 0
    #    uses: peter-evans/create-issue-from-file@v4
     #   with:
     #     title: Link Checker Report
     #    content-filepath: ./lychee/out.md
     #     labels: report, automated issue
